### ISSUE TITLE
函数的参数问题请教 |  a question about the function parameters

### ISSUE THREAD

**Issue by zhangyy103** [MrHause/ADS1115_Library#3]
您好，我是一名stm32初学者，在使用您的ads1115的驱动时，我发现在’ads1115.h'文件中  函数
'''C
void ADS1115_deinit();
int16_t ADS1115_getData();
int16_t ADS1115_oneShotMeasure();
’‘’
被声明为无参数类型，但是在‘ads1115.c’文件中，它们实现的时候具有参数
‘’‘C
ADS1115_Handle_t *pConfig
’‘’
尽管它们只会引起warnning但是我不太能理解这种写法，是因为您的疏忽还是这是一种特别的代码风格呢  
作为一名stm32初学者，我可能会提出错误的意见，请谅解。

---

Hello, I am a beginner with STM32. While using your ADS1115 driver, I noticed that in the `ads1115.h` file, the functions:
```C
void ADS1115_deinit();
int16_t ADS1115_getData();
int16_t ADS1115_oneShotMeasure();
```
are declared as having no parameters, but in the `ads1115.c` file, they are implemented with a parameter:
```C
ADS1115_Handle_t *pConfig
```
Even though this only causes warnings, I don't quite understand this approach. Is it an oversight on your part, or is it a special coding style? 

As a beginner with STM32, I might be making incorrect observations, please forgive me.

**Comment by Oerdna** [comment]
Hi @ZhangYangyang0550,

I think this is not a coding style, but a banal declaration error.
It needs to be corrected in the right way. But the author has not used github for a long time.

Therefore, if you want to fix/change something, it makes sense to make a **fork** of this project.

**Comment by MrHause** [comment]
Hi, I havent check github for longer time. Library was prepared for education purpose and never think someone will find it, therefor it can have some weak points. You are right about missing arguments in declarations. It's already fixed, and thank you for question.

**Comment by MrHause** [comment]
fixed
